/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alex_k8055_K8055Interface */

#ifndef _Included_com_alex_k8055_K8055Interface
#define _Included_com_alex_k8055_K8055Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    OpenDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_OpenDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    CloseDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alex_k8055_K8055Interface_CloseDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    ReadAnalogChannel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_ReadAnalogChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    ReadAllAnalog
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_ReadAllAnalog
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    OutputAnalogChannel
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_OutputAnalogChannel
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    OutputAllAnalog
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_OutputAllAnalog
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    ClearAnalogChannel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_ClearAnalogChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    ClearAllAnalog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_ClearAllAnalog
  (JNIEnv *, jclass);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    SetAnalogChannel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_SetAnalogChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    SetAllAnalog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_SetAllAnalog
  (JNIEnv *, jclass);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    WriteAllDigital
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_WriteAllDigital
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    ClearDigitalChannel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_ClearDigitalChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    ClearAllDigital
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_ClearAllDigital
  (JNIEnv *, jclass);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    SetDigitalChannel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_SetDigitalChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    SetAllDigital
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_SetAllDigital
  (JNIEnv *, jclass);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    ReadDigitalChannel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_ReadDigitalChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    ReadAllDigital
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_ReadAllDigital
  (JNIEnv *, jclass);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    ResetCounter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_ResetCounter
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    ReadCounter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_ReadCounter
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_alex_k8055_K8055Interface
 * Method:    SetCounterDebounceTime
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_alex_k8055_K8055Interface_SetCounterDebounceTime
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
